// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaSolarAPI.Data;

#nullable disable

namespace SistemaSolarAPI.Migrations
{
    [DbContext(typeof(SistemaSolarAPIContext))]
    [Migration("20221007045431_D1")]
    partial class D1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SistemaSolarAPI.Entities.Planeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Distancia")
                        .HasColumnType("int");

                    b.Property<int>("Massa")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<int>("SistemaSolarId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SistemaSolarId");

                    b.ToTable("Planetas", (string)null);
                });

            modelBuilder.Entity("SistemaSolarAPI.Entities.SistemaSolar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("MassaEstrela")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.HasKey("Id");

                    b.ToTable("SistemaSolares", (string)null);
                });

            modelBuilder.Entity("SistemaSolarAPI.Entities.Planeta", b =>
                {
                    b.HasOne("SistemaSolarAPI.Entities.SistemaSolar", "SistemaSolar")
                        .WithMany("Planetas")
                        .HasForeignKey("SistemaSolarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SistemaSolar");
                });

            modelBuilder.Entity("SistemaSolarAPI.Entities.SistemaSolar", b =>
                {
                    b.Navigation("Planetas");
                });
#pragma warning restore 612, 618
        }
    }
}
